site_name: Proppy

theme:
  name: "material"

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            merge_init_into_class: true

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
